[package]
name = "uniq"
version = "0.1.0"
authors = ["Bennett Hardwick <me@bennetthardwick.com>"]
edition = "2018"

[dependencies]

[dependencies.clap]
version = "2"
features = ["suggestions", "color", "wrap_help"]
